# Generated by Django 5.1.3 on 2024-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres_images/'),
        ),
    ]
