# Generated by Django 5.1.3 on 2024-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_livre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='emprunt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres/'),
        ),
    ]
