# Generated by Django 5.1.3 on 2024-11-28 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_livre_emprunt_count_alter_livre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.livre'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='nom_emprunteur',
            field=models.CharField(max_length=255),
        ),
    ]
